/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DataHistory.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samsamtu
 */
public class ViewandUpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewandUpdateJPanel
     */
    private Fleet fleet;
    
    public ViewandUpdateJPanel(Fleet fleet) throws ParseException {
        initComponents();
        this.fleet = fleet;
        populateTable(fleet.getFleet());
    }
    
    public void populateTable(ArrayList<Car> carList) throws ParseException {
        DefaultTableModel dtm = (DefaultTableModel) viewTable.getModel();
        dtm.setRowCount(0);

        //for(Car car : fleet.getAirliner()) {
        for (Car car : carList) {
            Object row[] = new Object[9];
            row[0] = car;
            row[1] = car.getAvailTime();
            row[2] = car.getCity();
            
            DateFormat format = new SimpleDateFormat("MM/dd/yyyy", Locale.ENGLISH);
            Date now = new Date();
            Date expiredTime = format.parse(car.getExpiredTime());
            row[3] = !expiredTime.after(now);

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uberYesBtn = new javax.swing.JRadioButton();
        uberNoBtn = new javax.swing.JRadioButton();
        availTimeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        manuYearComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modelNumTextField = new javax.swing.JTextField();
        viewDetailsBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveChangesBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        cityComboBox = new javax.swing.JComboBox<>();
        expiredTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        companyComboBox = new javax.swing.JComboBox<>();
        seatComboBox = new javax.swing.JComboBox<>();

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial Number", "Available Time", "Available City", "Mainten expired?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Company:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Serial Number:");

        serialNumTextField.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Available city(if available):");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Available time(YY/MM/DD):");

        buttonGroup1.add(uberYesBtn);
        uberYesBtn.setText("Yes");

        buttonGroup1.add(uberNoBtn);
        uberNoBtn.setText("No");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Made by Uber:");

        manuYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", " " }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Manufacture Year(1990-2000):");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Model Number:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Seats Number:");

        viewDetailsBtn.setText("View details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveChangesBtn.setText("Save changes");
        saveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlanda", "Boston", "Chicago", "Dallas", "DC", "Denver", "Houston", "Los Angeles", "Miami", "New York", "Orando", "San Francisco", "Seattle", " " }));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Maintenance certificate expired time:");

        companyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMW", "Ford", "GM", "Honda", "Jeep", "Mazda", "Mercedes-Benz", "Tesla", "Toyota", "Volkswagen", "Volvo", " ", " " }));

        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(viewDetailsBtn)
                        .addGap(42, 42, 42)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(uberYesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uberNoBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(expiredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(companyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seatComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(serialNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(modelNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(manuYearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 109, Short.MAX_VALUE)
                                    .addComponent(availTimeTextField)
                                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailsBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uberYesBtn)
                    .addComponent(uberNoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manuYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(companyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(saveChangesBtn)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed

      int selectedRow = viewTable.getSelectedRow();
      // when selecting a row
      if(selectedRow >= 0) {
         Car car = (Car)viewTable.getValueAt(selectedRow, 0);
         availTimeTextField.setText(String.valueOf(car.getAvailTime()));
         modelNumTextField.setText(String.valueOf(car.getModelNum()));
         seatComboBox.setSelectedIndex(car.getSeatsNum() - 2);
         serialNumTextField.setText(String.valueOf(car.getSerialNum()));
         expiredTextField.setText(car.getExpiredTime().toString());
                switch(car.getCompany()) {
                    case "BMW" : companyComboBox.setSelectedIndex(0);
                    break;
                    case "Ford" : companyComboBox.setSelectedIndex(1);
                    break;
                    case "GM" : companyComboBox.setSelectedIndex(2);
                    break;
                    case "Honda" : companyComboBox.setSelectedIndex(3);
                    break;
                    case "Jeep" : companyComboBox.setSelectedIndex(4);
                    break;
                    case "Mazda" : companyComboBox.setSelectedIndex(5);
                    break;
                    case "Mercedes-Benz" :companyComboBox.setSelectedIndex(6);
                    break;
                    case "Tesla" : companyComboBox.setSelectedIndex(7);
                    break;
                    case "Toyota" : companyComboBox.setSelectedIndex(8);
                    break;
                    case "Volkswagen" : companyComboBox.setSelectedIndex(9);
                    break;
                    case "Volvo" : companyComboBox.setSelectedIndex(10);
                    break;
                    
                }
                switch(car.getCity()) {
                    case "Atlanda" :  cityComboBox.setSelectedIndex(0);
                    break;
                    case "Boston" : cityComboBox.setSelectedIndex(1);
                    break;
                    case "Chicago" : cityComboBox.setSelectedIndex(2);
                    break;
                    case "Dallas" : cityComboBox.setSelectedIndex(3);
                    break;
                    case "DC" : cityComboBox.setSelectedIndex(4);
                    break;
                    case "Denver" : cityComboBox.setSelectedIndex(5);
                    break;
                    case "Houston" : cityComboBox.setSelectedIndex(6);
                    break;
                    case "Los Angeles" : cityComboBox.setSelectedIndex(7);
                    break;
                    case "Miami" : cityComboBox.setSelectedIndex(8);
                    break;
                    case "New York" : cityComboBox.setSelectedIndex(9);
                    break;
                    case "Orando" : cityComboBox.setSelectedIndex(10);
                    break;
                    case "San Francisco" : cityComboBox.setSelectedIndex(11);
                    break;
                    case "Seattle" : cityComboBox.setSelectedIndex(12);
                    break;
                }
         if(car.isUber()) uberYesBtn.setSelected(true);
         else uberNoBtn.setSelected(true);
         manuYearComboBox.setSelectedIndex(car.getManufactureYear()-1990);
//         SimpleDateFormat sdf = new SimpleDateFormat("MM:dd,HH:mm:ss"); 
//         updateTimeTextField.setText(sdf.format(car.getUpdateTime()));
      }
      //not selecting
      else {
         JOptionPane.showMessageDialog(null, "Please select any row!");
      }

// TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      int selectedRow = viewTable.getSelectedRow();
      // when selecting a row
      if(selectedRow >= 0) {
         Car car = (Car)viewTable.getValueAt(selectedRow, 0);
         fleet.deleteCar(car);
         JOptionPane.showMessageDialog(null, "Delete successfully!");
          try {
              //refresh
              populateTable(fleet.getFleet());
          } catch (ParseException ex) {
              Logger.getLogger(ViewandUpdateJPanel.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      //not selecting
      else {
         JOptionPane.showMessageDialog(null, "Please select any row!");
      }


// TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnActionPerformed

///there is only ONE Serial Number
    for (Car car : fleet.getFleet()) {
        if (car.getSerialNum() == Integer.parseInt(serialNumTextField.getText())) {
            car.setSeatsNum(Integer.parseInt(seatComboBox.getSelectedItem().toString()));
            car.setManufactureYear((Integer.parseInt(manuYearComboBox.getSelectedItem().toString())));
            car.setUber(uberYesBtn.isSelected());
            car.setSerialNum(Integer.parseInt(serialNumTextField.getText()));
            car.setCompany(companyComboBox.getSelectedItem().toString());
            car.setModelNum(Integer.parseInt(modelNumTextField.getText()));
            car.setCity(cityComboBox.getSelectedItem().toString());
            
            
            
            
           
            DateFormat format = new SimpleDateFormat("yyyy/MM/dd", Locale.ENGLISH);

            car.setAvailTime(availTimeTextField.getText());

            Date now = new Date();

            car.setExpiredTime(expiredTextField.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("MM:dd,HH:mm:ss"); 
            // show message when successfully saved
            JOptionPane.showMessageDialog(null, "update one car successfully! update time is: "+ sdf.format(now));
            //save update time
            car.setUpdateTime(format.format(now));
         
            }
        }
     
 
     
     
     //reset all values
     expiredTextField.setText("");
     companyComboBox.setSelectedIndex(0);
     modelNumTextField.setText("");
     seatComboBox.setSelectedIndex(0);
     serialNumTextField.setText("");
     cityComboBox.setSelectedIndex(0);
     availTimeTextField.setText("");
     buttonGroup1.clearSelection();
     buttonGroup2.clearSelection();
     manuYearComboBox.setSelectedIndex(0);
// TODO add your handling code here:
    }//GEN-LAST:event_saveChangesBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        
        try {
            populateTable(fleet.getFleet());
            
            
// TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(ViewandUpdateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availTimeTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JComboBox<String> companyComboBox;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField expiredTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> manuYearComboBox;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JComboBox<String> seatComboBox;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JRadioButton uberNoBtn;
    private javax.swing.JRadioButton uberYesBtn;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
