/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrphanageRole;

import Business.Organization.OrganizationDirectory;
import Business.OrphanageAdmin.ChildDetails;
import Business.OrphanageAdmin.ChildDetailsDirectory;
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prach
 */
public class ManageChildrenJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory;
    ChildDetailsDirectory cdd;

    /**
     * Creates new form ManageChildrenJPanel
     */
    public ManageChildrenJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory) {
        initComponents();

        this.organizationDirectory = organizationDirectory;
        //this.cdd=cdd;
        cdd = new ChildDetailsDirectory();
        this.userProcessContainer = userProcessContainer;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        childTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        downloadjButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Children");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        childTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First name", "Last Name", "Date of birth", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(childTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 114, 490, 120));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 281, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 328, -1, -1));

        jLabel4.setText("Date of Birth:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 377, -1, -1));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 415, -1, -1));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 278, 164, -1));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 325, 164, -1));

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 415, 164, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        downloadjButton.setText("Download details");
        downloadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadjButtonActionPerformed(evt);
            }
        });
        add(downloadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 160, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/nanshengtu/Downloads/WhatsApp Image 2018-04-27 at 1.53.01 AM.jpeg")); // NOI18N
        jLabel6.setText("jLabel2");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("MM-dd-yyyy");
        ChildDetails cd = new ChildDetails();
        ChildDetails cde = cdd.createChildDetails(cd);
        cde.setFirstName(firstNameTextField.getText());
        cde.setLastName(lastNameTextField.getText());
        
        
        Date currentDate = new Date();
        Date choseDate = jDateChooser1.getDate();
        if (currentDate.after(choseDate)) {    
            JOptionPane.showMessageDialog(null, "Please input previous date");
        }
      
        String date = dFormat.format(jDateChooser1.getDate());    
        cde.setDob(date);
        
        String age = ageTextField.getText();
        
        if (!age.matches("-?\\d+")) {
            JOptionPane.showMessageDialog(null, "Please input only digits");
        }
        
        
        cde.setAge(Integer.parseInt(age));  
        //refresh
        refreshTable();
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void downloadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadjButtonActionPerformed
        // TODO add your handling code here:
        //File file = new File("C:\\NEU\\AED_SPRING_2018\\Project\\children.xls");

        String filePath = "data//children.csv";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("FirstName,LastName,DOB,Age");
            bw.newLine();
            for (int i = 0; i < childTable.getRowCount(); i++) {
                for (int j = 0; j < childTable.getColumnCount(); j++) {
                    bw.write(childTable.getValueAt(i, j).toString() + ",");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(ManageChildrenJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Report Downloaded Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_downloadjButtonActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    public void refreshTable() {
        DefaultTableModel dtm = (DefaultTableModel) childTable.getModel();
        dtm.setRowCount(0);

        for (ChildDetails cd : cdd.getChildDetailsList()) {
            Object[] row = new Object[4];
            row[0] = cd;
            row[1] = cd.getLastName();
            row[2] = cd.getDob();
            row[3] = cd.getAge();
            dtm.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTable childTable;
    private javax.swing.JButton downloadjButton;
    private javax.swing.JTextField firstNameTextField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTextField;
    // End of variables declaration//GEN-END:variables
}
