/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.OrphanageRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.OrphanageEnterprise;
import Business.Network.Network;
import Business.OrphanageAdmin.ChildDetails;
import Business.OrphanageAdmin.ChildDetailsDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class OrphanageWorkAreaJPanel extends javax.swing.JPanel {
    
    private ChildDetails cd;
    JPanel userProcessContainer;
    OrphanageEnterprise enterprise;
    ChildDetailsDirectory cdd;
    UserAccount account;
    Network network;
 
   // UserAccount account;
    /** Creates new form AdminWorkAreaJPanel */
    public OrphanageWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (OrphanageEnterprise)enterprise;
        this.network = network;
        this.account = account;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageChildrenJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageAdoptersButton = new javax.swing.JButton();
        manageOrphanageButton = new javax.swing.JButton();
        seeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, -1));

        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, -1));

        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 30));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, -1));

        manageChildrenJButton.setText("Manage Children");
        manageChildrenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageChildrenJButtonActionPerformed(evt);
            }
        });
        add(manageChildrenJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, -1));

        jButton1.setText("Send data to school");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 210, -1));

        manageAdoptersButton.setText("Manage Adopters");
        manageAdoptersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdoptersButtonActionPerformed(evt);
            }
        });
        add(manageAdoptersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 190, -1));

        manageOrphanageButton.setText("Manage orphanage details");
        manageOrphanageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrphanageButtonActionPerformed(evt);
            }
        });
        add(manageOrphanageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        seeBtn.setText("See Request funds from company");
        seeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeBtnActionPerformed(evt);
            }
        });
        add(seeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/nanshengtu/Downloads/WhatsApp Image 2018-04-27 at 1.53.01 AM.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        if (enterprise.getAdd() == null) System.out.print("enterprise.getAdd() is null");
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise.getCdd(),enterprise.getAdd());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageChildrenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageChildrenJButtonActionPerformed
        // TODO add your handling code here:
        ManageChildrenJPanel manageChildrenJPanel = new ManageChildrenJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageChildrenJPanel", manageChildrenJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
 
    }//GEN-LAST:event_manageChildrenJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SendChildrenDetailsToSchoolJPanel scdjpanel = new SendChildrenDetailsToSchoolJPanel(userProcessContainer, account, network);
        userProcessContainer.add("scdjpanel", scdjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageAdoptersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdoptersButtonActionPerformed
        // TODO add your handling code here:
        ManageAdoptersJPanel pijpanel = new ManageAdoptersJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("pijpanel", pijpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdoptersButtonActionPerformed

    private void manageOrphanageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrphanageButtonActionPerformed
        // TODO add your handling code here:
        ManageOrphanageDetailsJPanel modjpanel = new ManageOrphanageDetailsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("modjpanel", modjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrphanageButtonActionPerformed

    private void seeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeBtnActionPerformed
        // TODO add your handling code here:
        RequestFundsFromCompanyJPanel r = new RequestFundsFromCompanyJPanel(userProcessContainer, account, enterprise, enterprise.getOrganizationDirectory());
        userProcessContainer.add("r", r);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_seeBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAdoptersButton;
    private javax.swing.JButton manageChildrenJButton;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageOrphanageButton;
    private javax.swing.JButton seeBtn;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
